### ISSUE TITLE
facing some error 

### ISSUE THREAD

**Issue by CSR-SOFTWARES** [tom-snow/PyroEdgeGPTBot#11]
File "/PyroEdgeGptBot/PyroEdgeGptBot.py", line 755, in bingAI
rsp = await EDGES[user_id]["bot"].ask(prompt=messageText, conversation_style=EDGES[user_id]["style"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/EdgeGPT.py", line 659, in ask
async for final, response in self.chat_hub.ask_stream(
File "/usr/local/lib/python3.11/site-packages/EdgeGPT.py", line 556, in ask_stream
raise Exception(
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

**Comment by CSR-SOFTWARES** [comment]
from morning its same

**Comment by tom-snow** [comment]
> site-packages/EdgeGPT.py

if you find this in log, it means upstream error. You should not ask me!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Try update cookie, EdgeGPT version, or report to upstream. Don't bother me if you meet upstream error.

**Comment by tom-snow** [comment]
Other things, this error may means your request has been flagged as bot. Try change you ip to send request to BingAI

**Comment by CSR-SOFTWARES** [comment]
okay thanks !
