### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by DULPALAMAKUMBURA** [tom-snow/PyroEdgeGPTBot#19]
Traceback (most recent call last):
  File "PyroEdgeGptBot.py", line 80, in <module>
    if not check_conversation_style(DEFAULT_CONVERSATION_STYLE_TYPE):
  File "PyroEdgeGptBot.py", line 76, in check_conversation_style
    if style in EdgeGPT.ConversationStyle.__members__:
AttributeError: module 'EdgeGPT' has no attribute 'ConversationStyle'

**Comment by tom-snow** [comment]
I hate upstream repo.
They Always changes the API.

**Comment by tom-snow** [comment]
Hate Microsoft too! 
They add the CaptchaChallenge. The bot I deploy on railway can not work now.

**Comment by tom-snow** [comment]
> Traceback (most recent call last):
> File "PyroEdgeGptBot.py", line 80, in 
> if not check_conversation_style(DEFAULT_CONVERSATION_STYLE_TYPE):
> File "PyroEdgeGptBot.py", line 76, in check_conversation_style
> if style in EdgeGPT.ConversationStyle.**members**:
> AttributeError: module 'EdgeGPT' has no attribute 'ConversationStyle'

This may fixed. On my vps the bot works well now

**Comment by tom-snow** [comment]
If you face the CaptchaChallenge like:
![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/79245287/e1248af3-437d-4428-a2c8-620af6a3ff62)

Wait upstream fix or change your IP (change vps or using proxy)

**Comment by DULPALAMAKUMBURA** [comment]
ok problem lies within the release v2.0, but PyroEdgeGptBot.py in commit is updated. So download the commit as a zip
