### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by Grachoow** [tom-snow/PyroEdgeGPTBot#2]
![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/117411147/1198badb-7da5-4bf4-95d9-96a23d4052f7)

Good afternoon I got this error, maybe I'm doing something wrong, because I'm not very good at it. I tried to run through the command line, and also tried to run through powershell. Thanks in advance for your reply.

**Comment by tom-snow** [comment]
This is a bug on windows ( because of the windows using different types of file path, I’ll fixing it soon)

**Comment by tom-snow** [comment]
Try to download the newest code

**Comment by Grachoow** [comment]
![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/117411147/dcfb33e4-7b4d-43c3-a5ab-0bb4508c6d31)
Hello! I did it, thanks a lot! I noticed an inaccuracy in the manual - you need to create a file cookie.json, not cookies.json.

**Comment by tom-snow** [comment]
> ![image](https://user-images.githubusercontent.com/117411147/238258395-dcfb33e4-7b4d-43c3-a5ab-0bb4508c6d31.png)
> Hello! I did it, thanks a lot! I noticed an inaccuracy in the manual - you need to create a file cookie.json, not cookies.json.

Fixed. Thanks
