### ISSUE TITLE
what about image generation ?

### ISSUE THREAD

**Issue by CSR-SOFTWARES** [tom-snow/PyroEdgeGPTBot#3]
this script only send those 5 stored images for every prompt , was this error on my side or its issue in script only ?

if its on my side then do pls explain me that how I can solve this issue ?

**Comment by tom-snow** [comment]
It will response 4 pictures default, then using bing AI returned images to replace it

**Comment by CSR-SOFTWARES** [comment]
alright let me try this one if any error will update .
thank You so much for Your time

**Comment by tom-snow** [comment]
Or you can using inline mode, you should contact @botfather and unlock inline mode for your bot first. And then at any where to @YourBotUserName and input prompt

**Comment by CSR-SOFTWARES** [comment]
I tried the same in past but did not worked

**Comment by CSR-SOFTWARES** [comment]
point is that I am still learning python so making some of changes in Your code

**Comment by tom-snow** [comment]
Could you give me a screenshot of the conversation about you using /image_gen and the bot’s response.

If send the log file too will be better

**Comment by CSR-SOFTWARES** [comment]
sure sharing You in just some minutes

**Comment by CSR-SOFTWARES** [comment]
![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/90786270/477e34e2-2823-45c8-be79-93152c0d4aea)
![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/90786270/53f8c41b-d09d-49e7-aaff-6f89a71ebf1b)
![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/90786270/a3c5cfee-2555-4536-bd5c-fe0ae7182fa0)
![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/90786270/50c4e938-e636-4807-a582-b7505735a7a6)
![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/90786270/8b693d62-cffa-4295-8dc7-075e8d8159f9)
[PyroEdgeGptBot.log](https://github.com/tom-snow/PyroEdgeGPTBot/files/11468797/PyroEdgeGptBot.log)

**Comment by CSR-SOFTWARES** [comment]
here above I shared Screenshot of conversation between me and bot 
also some ss of the windows shell 
and further log file

**Comment by tom-snow** [comment]
> here is the username of the @TESTCSRBOT at telegram

Humm, other people can not use your bot except you set them userID in ALLOWED_IDS.

I can’t test the bot this time ( my bot should renew the cookies and I am not at my computer )

**Comment by CSR-SOFTWARES** [comment]
But I don't removed Your defalut id 

also if You want give Your any int id I will added it to allowed list\

**Comment by tom-snow** [comment]
6083945456

**Comment by CSR-SOFTWARES** [comment]
added

**Comment by CSR-SOFTWARES** [comment]
@I_AM_CSR 
is my tg id if anything pls text me over that

**Comment by tom-snow** [comment]
https://github.com/tom-snow/PyroEdgeGPTBot/assets/79245287/4c9dca17-49c7-4eea-b222-e7bcb378de61

**Comment by CSR-SOFTWARES** [comment]
alright got it !
thank You so much 

also can You tell me a platform where I can host this script for free ?
like I first through of pythonanywhere but It don't supports Pygram session 
so any platform which is free and support this script

**Comment by tom-snow** [comment]
https://railway.app/

**Comment by CSR-SOFTWARES** [comment]
okay thank You
