### ISSUE TITLE
Error on every second message

### ISSUE THREAD

**Issue by CSR-SOFTWARES** [tom-snow/PyroEdgeGPTBot#4]
File "/opt/render/project/src/.venv/lib/python3.8/site-packages/EdgeGPT.py", line 555, in ask_stream
May 14 07:21:33 PM      response["item"]["messages"][-1]["contentOrigin"] == "Apology"
May 14 07:21:33 PM  KeyError: 'messages'

**Comment by tom-snow** [comment]
this is the upstream error ( seems You sent a sensitive message that the bot refuses to reply )
