### ISSUE TITLE
what's the update in New version ?

### ISSUE THREAD

**Issue by CSR-SOFTWARES** [tom-snow/PyroEdgeGPTBot#5]
what features or assistance will get through this new updated version??

**Comment by tom-snow** [comment]
Just keep updated is recommended.

Add `/update` command , using this will update the EdgeGPT to the newest. ( only update EdgeGPT, not [PyroEdgeGPTBot](https://github.com/tom-snow/PyroEdgeGPTBot))

**Comment by CSR-SOFTWARES** [comment]
Okays Thanks
