### ISSUE TITLE
Back4app NO RESPONSE 

### ISSUE THREAD

**Issue by CSR-SOFTWARES** [tom-snow/PyroEdgeGPTBot#7]
HOW MUCH TIME IT WILL TAKE TO GET DEPLOYED ?

showing deploying from last  10 mins  ...............

no response after hiting deploy button 
JUST SHOWING DEPLOYING

![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/90786270/43eb7ffa-864d-4167-b139-5f44083e4fdd)
![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/90786270/48b1be7e-a59d-4134-9b55-7b8d96ef4df8)
![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/90786270/d4e26642-96d7-4339-9b91-84fb24e08c5a)

**Comment by tom-snow** [comment]
Try another platform. This may the mistake of back4app now

**Comment by CSR-SOFTWARES** [comment]
which platform ??

**Comment by tom-snow** [comment]
Such as railway
