### ISSUE TITLE
image gen not fixed !

### ISSUE THREAD

**Issue by CSR-SOFTWARES** [tom-snow/PyroEdgeGPTBot#8]
ImageGenerator Error: Redirect failed.

ImageGenerator Usage: /image_gen <prompt>

also I tried the script on Render 
it got build and running well...
but as script not end the building/deploying process at any istance 
it always shows deploying 
as of the conditions of render anything not deployed within 15 mins , get terminated and shows deployed failed 

pls fixed these bugs !

**Comment by tom-snow** [comment]
![image](https://github.com/tom-snow/PyroEdgeGPTBot/assets/79245287/48c7cec0-5aaf-451b-97bf-aba5cbfd86d4)


every thing works well, it's your problem!

update cookie. when you see "Redirect failed."

**Comment by tom-snow** [comment]
[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/template/7OO3yS?referralCode=_cP9IT)
