### ISSUE TITLE
getting this error , what to do ?

### ISSUE THREAD

**Issue by CSR-SOFTWARES** [tom-snow/PyroEdgeGPTBot#9]
2023-05-19 09:27:55 - pyrogram.dispatcher - ERROR - Throttled: Request is throttled.
Traceback (most recent call last):
File "/PyroEdgeGptBot/PyroEdgeGptBot.py", line 663, in bingAI
rsp = await EDGES[user_id]["bot"].ask(prompt=messageText, conversation_style=EDGES[user_id]["style"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/EdgeGPT.py", line 659, in ask
async for final, response in self.chat_hub.ask_stream(
File "/usr/local/lib/python3.11/site-packages/EdgeGPT.py", line 556, in ask_stream
raise Exception(
Exception: Throttled: Request is throttled.

**Comment by CSR-SOFTWARES** [comment]
Every message to bot, prints this error 

even updated the cookie

**Comment by tom-snow** [comment]
what did you ask? seems bot refuse to answer.

**Comment by CSR-SOFTWARES** [comment]
It was simple study based questions

**Comment by tom-snow** [comment]
Don't keep trying sensitive content, you may be flagged or banned

**Comment by CSR-SOFTWARES** [comment]
One thing more 
Will get any updated version in future?

**Comment by CSR-SOFTWARES** [comment]
I mean will get any updated version of it 

Suggestion for the future feature

I need force join feature
Every user who is using it should join particular channel or group

**Comment by tom-snow** [comment]
Not planed. This is just a small project. People can exchange their experiences at GitHub issue or discussion( if any people need ).

This time this project only have a few users. And may no more feature will be add to this project( bug fixes will still ).
